"""Constants for Datum Display integration."""
from typing import Final

DOMAIN: Final = "datum_display"
CONF_LANGUAGE: Final = "language"
CONF_DATE_FORMAT: Final = "date_format"
CONF_SENSORS: Final = "sensors"

# Available languages
LANGUAGE_CS: Final = "cs"
LANGUAGE_EN: Final = "en"

LANGUAGES: Final = {
    LANGUAGE_CS: "Čeština",
    LANGUAGE_EN: "English",
}

# Date format identifiers
FORMAT_DD_MM_YYYY_DOT: Final = "dd.mm.yyyy"
FORMAT_DD_MM_YYYY_DOT_SPACE: Final = "dd. mm. yyyy"
FORMAT_D_M_YYYY_DOT: Final = "d.m.yyyy"
FORMAT_DD_MM_YYYY_SLASH: Final = "dd/mm/yyyy"
FORMAT_MM_DD_YYYY_SLASH: Final = "mm/dd/yyyy"
FORMAT_YYYY_MM_DD: Final = "yyyy-mm-dd"
FORMAT_DD_MONTH_YYYY: Final = "dd_month_yyyy"
FORMAT_DAY_DD_MONTH_YYYY: Final = "day_dd_month_yyyy"
FORMAT_DAY_DD_MONTH: Final = "day_dd_month"
FORMAT_DD_MONTH: Final = "dd_month"
FORMAT_DAY_SHORT_DD_MM: Final = "day_short_dd_mm"
FORMAT_DAY_ABBR_DD_MM: Final = "day_abbr_dd_mm"
FORMAT_ISO8601: Final = "iso8601"
FORMAT_RELATIVE: Final = "relative"
FORMAT_VERBAL: Final = "verbal"

DATE_FORMATS: Final = {
    FORMAT_DD_MM_YYYY_DOT: "DD.MM.YYYY",
    FORMAT_DD_MM_YYYY_DOT_SPACE: "DD. MM. YYYY",
    FORMAT_D_M_YYYY_DOT: "D.M.YYYY",
    FORMAT_DD_MM_YYYY_SLASH: "DD/MM/YYYY",
    FORMAT_MM_DD_YYYY_SLASH: "MM/DD/YYYY",
    FORMAT_YYYY_MM_DD: "YYYY-MM-DD",
    FORMAT_DD_MONTH_YYYY: "DD. měsíc YYYY",
    FORMAT_DAY_DD_MONTH_YYYY: "Den DD. měsíc YYYY",
    FORMAT_DAY_DD_MONTH: "Den DD. měsíc",
    FORMAT_DD_MONTH: "DD měsíc",
    FORMAT_DAY_SHORT_DD_MM: "Den, DD.MM.",
    FORMAT_DAY_ABBR_DD_MM: "Zkr. den DD.MM.",
    FORMAT_ISO8601: "ISO 8601",
    FORMAT_RELATIVE: "Relativní (Dnes/Včera...)",
    FORMAT_VERBAL: "Slovní",
}

# Sensor types
SENSOR_DATE: Final = "date"
SENSOR_DAY_NAME: Final = "day_name"
SENSOR_DAY_NAME_SHORT: Final = "day_name_short"
SENSOR_WEEK_NUMBER: Final = "week_number"
SENSOR_MONTH_NAME: Final = "month_name"
SENSOR_MONTH_NUMBER: Final = "month_number"
SENSOR_YEAR: Final = "year"
SENSOR_DAY_OF_YEAR: Final = "day_of_year"
SENSOR_DAYS_IN_MONTH: Final = "days_in_month"
SENSOR_IS_LEAP_YEAR: Final = "is_leap_year"
SENSOR_QUARTER: Final = "quarter"
SENSOR_DAYS_UNTIL_END_OF_YEAR: Final = "days_until_end_of_year"
SENSOR_WEEK_DATES: Final = "week_dates"
SENSOR_TOMORROW: Final = "tomorrow"
SENSOR_YESTERDAY: Final = "yesterday"
SENSOR_WEEK_START: Final = "week_start"
SENSOR_WEEK_END: Final = "week_end"
SENSOR_HOLIDAY: Final = "holiday"
SENSOR_NAME_DAY: Final = "name_day"
SENSOR_IS_WORKDAY: Final = "is_workday"
SENSOR_MOON_PHASE: Final = "moon_phase"
SENSOR_SEASON: Final = "season"
SENSOR_ZODIAC: Final = "zodiac"
SENSOR_DAYS_UNTIL_CHRISTMAS: Final = "days_until_christmas"
SENSOR_DAYS_UNTIL_NEW_YEAR: Final = "days_until_new_year"
SENSOR_DAYS_UNTIL_EASTER: Final = "days_until_easter"
SENSOR_WORKDAYS_IN_MONTH: Final = "workdays_in_month"
SENSOR_WORKDAYS_LEFT: Final = "workdays_left"

SENSOR_TYPES: Final = {
    SENSOR_DATE: "Datum",
    SENSOR_DAY_NAME: "Název dne",
    SENSOR_DAY_NAME_SHORT: "Zkrácený název dne",
    SENSOR_WEEK_NUMBER: "Číslo týdne",
    SENSOR_MONTH_NAME: "Název měsíce",
    SENSOR_MONTH_NUMBER: "Číslo měsíce",
    SENSOR_YEAR: "Rok",
    SENSOR_DAY_OF_YEAR: "Den v roce",
    SENSOR_DAYS_IN_MONTH: "Počet dnů v měsíci",
    SENSOR_IS_LEAP_YEAR: "Přestupný rok",
    SENSOR_QUARTER: "Čtvrtletí",
    SENSOR_DAYS_UNTIL_END_OF_YEAR: "Dnů do konce roku",
    SENSOR_WEEK_DATES: "Data týdne",
    SENSOR_TOMORROW: "Zítra",
    SENSOR_YESTERDAY: "Včera",
    SENSOR_WEEK_START: "Začátek týdne",
    SENSOR_WEEK_END: "Konec týdne",
    SENSOR_HOLIDAY: "Svátek",
    SENSOR_NAME_DAY: "Jmeniny",
    SENSOR_IS_WORKDAY: "Pracovní den",
    SENSOR_MOON_PHASE: "Fáze měsíce",
    SENSOR_SEASON: "Roční období",
    SENSOR_ZODIAC: "Znamení zvěrokruhu",
    SENSOR_DAYS_UNTIL_CHRISTMAS: "Dnů do Vánoc",
    SENSOR_DAYS_UNTIL_NEW_YEAR: "Dnů do Nového roku",
    SENSOR_DAYS_UNTIL_EASTER: "Dnů do Velikonoc",
    SENSOR_WORKDAYS_IN_MONTH: "Pracovních dnů v měsíci",
    SENSOR_WORKDAYS_LEFT: "Zbývá pracovních dnů",
}

# Czech day names
DAYS_CS: Final = {
    0: "Pondělí",
    1: "Úterý",
    2: "Středa",
    3: "Čtvrtek",
    4: "Pátek",
    5: "Sobota",
    6: "Neděle",
}

DAYS_CS_SHORT: Final = {
    0: "Po",
    1: "Út",
    2: "St",
    3: "Čt",
    4: "Pá",
    5: "So",
    6: "Ne",
}

# English day names
DAYS_EN: Final = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}

DAYS_EN_SHORT: Final = {
    0: "Mon",
    1: "Tue",
    2: "Wed",
    3: "Thu",
    4: "Fri",
    5: "Sat",
    6: "Sun",
}

# Czech month names (nominative)
MONTHS_CS: Final = {
    1: "Leden",
    2: "Únor",
    3: "Březen",
    4: "Duben",
    5: "Květen",
    6: "Červen",
    7: "Červenec",
    8: "Srpen",
    9: "Září",
    10: "Říjen",
    11: "Listopad",
    12: "Prosinec",
}

# Czech month names (genitive - for dates like "25. ledna")
MONTHS_CS_GENITIVE: Final = {
    1: "ledna",
    2: "února",
    3: "března",
    4: "dubna",
    5: "května",
    6: "června",
    7: "července",
    8: "srpna",
    9: "září",
    10: "října",
    11: "listopadu",
    12: "prosince",
}

# English month names
MONTHS_EN: Final = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
}

# Relative date translations
RELATIVE_CS: Final = {
    -2: "Předevčírem",
    -1: "Včera",
    0: "Dnes",
    1: "Zítra",
    2: "Pozítří",
}

RELATIVE_EN: Final = {
    -2: "Day before yesterday",
    -1: "Yesterday",
    0: "Today",
    1: "Tomorrow",
    2: "Day after tomorrow",
}

# Czech ordinal numbers for verbal dates (1-31)
ORDINALS_CS: Final = {
    1: "Prvního",
    2: "Druhého",
    3: "Třetího",
    4: "Čtvrtého",
    5: "Pátého",
    6: "Šestého",
    7: "Sedmého",
    8: "Osmého",
    9: "Devátého",
    10: "Desátého",
    11: "Jedenáctého",
    12: "Dvanáctého",
    13: "Třináctého",
    14: "Čtrnáctého",
    15: "Patnáctého",
    16: "Šestnáctého",
    17: "Sedmnáctého",
    18: "Osmnáctého",
    19: "Devatenáctého",
    20: "Dvacátého",
    21: "Dvacátého prvního",
    22: "Dvacátého druhého",
    23: "Dvacátého třetího",
    24: "Dvacátého čtvrtého",
    25: "Dvacátého pátého",
    26: "Dvacátého šestého",
    27: "Dvacátého sedmého",
    28: "Dvacátého osmého",
    29: "Dvacátého devátého",
    30: "Třicátého",
    31: "Třicátého prvního",
}

# English ordinal numbers for verbal dates (1-31)
ORDINALS_EN: Final = {
    1: "First",
    2: "Second",
    3: "Third",
    4: "Fourth",
    5: "Fifth",
    6: "Sixth",
    7: "Seventh",
    8: "Eighth",
    9: "Ninth",
    10: "Tenth",
    11: "Eleventh",
    12: "Twelfth",
    13: "Thirteenth",
    14: "Fourteenth",
    15: "Fifteenth",
    16: "Sixteenth",
    17: "Seventeenth",
    18: "Eighteenth",
    19: "Nineteenth",
    20: "Twentieth",
    21: "Twenty-first",
    22: "Twenty-second",
    23: "Twenty-third",
    24: "Twenty-fourth",
    25: "Twenty-fifth",
    26: "Twenty-sixth",
    27: "Twenty-seventh",
    28: "Twenty-eighth",
    29: "Twenty-ninth",
    30: "Thirtieth",
    31: "Thirty-first",
}

# Czech state holidays (month, day): name
HOLIDAYS_CS: Final = {
    (1, 1): "Nový rok / Den obnovy samostatného českého státu",
    (5, 1): "Svátek práce",
    (5, 8): "Den vítězství",
    (7, 5): "Den slovanských věrozvěstů Cyrila a Metoděje",
    (7, 6): "Den upálení mistra Jana Husa",
    (9, 28): "Den české státnosti",
    (10, 28): "Den vzniku samostatného československého státu",
    (11, 17): "Den boje za svobodu a demokracii",
    (12, 24): "Štědrý den",
    (12, 25): "1. svátek vánoční",
    (12, 26): "2. svátek vánoční",
}

# English holidays
HOLIDAYS_EN: Final = {
    (1, 1): "New Year's Day",
    (5, 1): "Labour Day",
    (5, 8): "Victory Day",
    (7, 5): "Saints Cyril and Methodius Day",
    (7, 6): "Jan Hus Day",
    (9, 28): "Czech Statehood Day",
    (10, 28): "Czechoslovak Independence Day",
    (11, 17): "Struggle for Freedom and Democracy Day",
    (12, 24): "Christmas Eve",
    (12, 25): "Christmas Day",
    (12, 26): "St. Stephen's Day",
}

# Czech name days (month, day): names
NAME_DAYS_CS: Final = {
    (1, 1): "Nový rok",
    (1, 2): "Karina",
    (1, 3): "Radmila",
    (1, 4): "Diana",
    (1, 5): "Dalimil",
    (1, 6): "Tři králové",
    (1, 7): "Vilma",
    (1, 8): "Čestmír",
    (1, 9): "Vladan",
    (1, 10): "Břetislav",
    (1, 11): "Bohdana",
    (1, 12): "Pravoslav",
    (1, 13): "Edita",
    (1, 14): "Radovan",
    (1, 15): "Alice",
    (1, 16): "Ctirad",
    (1, 17): "Drahoslav",
    (1, 18): "Vladislav",
    (1, 19): "Doubravka",
    (1, 20): "Ilona",
    (1, 21): "Běla",
    (1, 22): "Slavomír",
    (1, 23): "Zdeněk",
    (1, 24): "Milena",
    (1, 25): "Miloš",
    (1, 26): "Zora",
    (1, 27): "Ingrid",
    (1, 28): "Otýlie",
    (1, 29): "Zdislava",
    (1, 30): "Robin",
    (1, 31): "Marika",
    (2, 1): "Hynek",
    (2, 2): "Nela",
    (2, 3): "Blažej",
    (2, 4): "Jarmila",
    (2, 5): "Dobromila",
    (2, 6): "Vanda",
    (2, 7): "Veronika",
    (2, 8): "Milada",
    (2, 9): "Apolena",
    (2, 10): "Mojmír",
    (2, 11): "Božena",
    (2, 12): "Slavěna",
    (2, 13): "Věnceslav",
    (2, 14): "Valentýn",
    (2, 15): "Jiřina",
    (2, 16): "Ljuba",
    (2, 17): "Miloslava",
    (2, 18): "Gizela",
    (2, 19): "Patrik",
    (2, 20): "Oldřich",
    (2, 21): "Lenka",
    (2, 22): "Petr",
    (2, 23): "Svatopluk",
    (2, 24): "Matěj",
    (2, 25): "Liliana",
    (2, 26): "Dorota",
    (2, 27): "Alexandr",
    (2, 28): "Lumír",
    (2, 29): "Horymír",
    (3, 1): "Bedřich",
    (3, 2): "Anežka",
    (3, 3): "Kamil",
    (3, 4): "Stela",
    (3, 5): "Kazimír",
    (3, 6): "Miroslav",
    (3, 7): "Tomáš",
    (3, 8): "Gabriela",
    (3, 9): "Františka",
    (3, 10): "Viktorie",
    (3, 11): "Anděla",
    (3, 12): "Řehoř",
    (3, 13): "Růžena",
    (3, 14): "Rút, Matylda",
    (3, 15): "Ida",
    (3, 16): "Elena, Herbert",
    (3, 17): "Vlastimil",
    (3, 18): "Eduard",
    (3, 19): "Josef",
    (3, 20): "Světlana",
    (3, 21): "Radek",
    (3, 22): "Leona",
    (3, 23): "Ivona",
    (3, 24): "Gabriel",
    (3, 25): "Marián",
    (3, 26): "Emanuel",
    (3, 27): "Dita",
    (3, 28): "Soňa",
    (3, 29): "Taťána",
    (3, 30): "Arnošt",
    (3, 31): "Kvido",
    (4, 1): "Hugo",
    (4, 2): "Erika",
    (4, 3): "Richard",
    (4, 4): "Ivana",
    (4, 5): "Miroslava",
    (4, 6): "Vendula",
    (4, 7): "Heřman, Hermína",
    (4, 8): "Ema",
    (4, 9): "Dušan",
    (4, 10): "Darja",
    (4, 11): "Izabela",
    (4, 12): "Julius",
    (4, 13): "Aleš",
    (4, 14): "Vincenc",
    (4, 15): "Anastázie",
    (4, 16): "Irena",
    (4, 17): "Rudolf",
    (4, 18): "Valérie",
    (4, 19): "Rostislav",
    (4, 20): "Marcela",
    (4, 21): "Alexandra",
    (4, 22): "Evženie",
    (4, 23): "Vojtěch",
    (4, 24): "Jiří",
    (4, 25): "Marek",
    (4, 26): "Oto",
    (4, 27): "Jaroslav",
    (4, 28): "Vlastislav",
    (4, 29): "Robert",
    (4, 30): "Blahoslav",
    (5, 1): "Svátek práce",
    (5, 2): "Zikmund",
    (5, 3): "Alexej",
    (5, 4): "Květoslav",
    (5, 5): "Klaudie",
    (5, 6): "Radoslav",
    (5, 7): "Stanislav",
    (5, 8): "Den vítězství",
    (5, 9): "Ctibor",
    (5, 10): "Blažena",
    (5, 11): "Svatava",
    (5, 12): "Pankrác",
    (5, 13): "Servác",
    (5, 14): "Bonifác",
    (5, 15): "Žofie",
    (5, 16): "Přemysl",
    (5, 17): "Aneta",
    (5, 18): "Nataša",
    (5, 19): "Ivo",
    (5, 20): "Zbyšek",
    (5, 21): "Monika",
    (5, 22): "Emil",
    (5, 23): "Vladimír",
    (5, 24): "Jana",
    (5, 25): "Viola",
    (5, 26): "Filip",
    (5, 27): "Valdemar",
    (5, 28): "Vilém",
    (5, 29): "Maxmilián",
    (5, 30): "Ferdinand",
    (5, 31): "Kamila",
    (6, 1): "Laura",
    (6, 2): "Jarmil",
    (6, 3): "Tamara",
    (6, 4): "Dalibor",
    (6, 5): "Dobroslav",
    (6, 6): "Norbert",
    (6, 7): "Iveta, Slavoj",
    (6, 8): "Medard",
    (6, 9): "Stanislava",
    (6, 10): "Gita",
    (6, 11): "Bruno",
    (6, 12): "Antonie",
    (6, 13): "Antonín",
    (6, 14): "Roland",
    (6, 15): "Vít",
    (6, 16): "Zbyněk",
    (6, 17): "Adolf",
    (6, 18): "Milan",
    (6, 19): "Leoš",
    (6, 20): "Květa",
    (6, 21): "Alois",
    (6, 22): "Pavla",
    (6, 23): "Zdeňka",
    (6, 24): "Jan",
    (6, 25): "Ivan",
    (6, 26): "Adriana",
    (6, 27): "Ladislav",
    (6, 28): "Lubomír",
    (6, 29): "Petr a Pavel",
    (6, 30): "Šárka",
    (7, 1): "Jaroslava",
    (7, 2): "Patricie",
    (7, 3): "Radomír",
    (7, 4): "Prokop",
    (7, 5): "Cyril a Metoděj",
    (7, 6): "Mistr Jan Hus",
    (7, 7): "Bohuslava",
    (7, 8): "Nora",
    (7, 9): "Drahoslava",
    (7, 10): "Libuše, Amálie",
    (7, 11): "Olga",
    (7, 12): "Bořek",
    (7, 13): "Markéta",
    (7, 14): "Karolína",
    (7, 15): "Jindřich",
    (7, 16): "Luboš",
    (7, 17): "Martina",
    (7, 18): "Drahomíra",
    (7, 19): "Čeněk",
    (7, 20): "Ilja",
    (7, 21): "Vítězslav",
    (7, 22): "Magdaléna",
    (7, 23): "Libor",
    (7, 24): "Kristýna",
    (7, 25): "Jakub",
    (7, 26): "Anna",
    (7, 27): "Věroslav",
    (7, 28): "Viktor",
    (7, 29): "Marta",
    (7, 30): "Bořivoj",
    (7, 31): "Ignác",
    (8, 1): "Oskar",
    (8, 2): "Gustav",
    (8, 3): "Miluše",
    (8, 4): "Dominik",
    (8, 5): "Kristian",
    (8, 6): "Oldřiška",
    (8, 7): "Lada",
    (8, 8): "Soběslav",
    (8, 9): "Roman",
    (8, 10): "Vavřinec",
    (8, 11): "Zuzana",
    (8, 12): "Klára",
    (8, 13): "Alena",
    (8, 14): "Alan",
    (8, 15): "Hana",
    (8, 16): "Jáchym",
    (8, 17): "Petra",
    (8, 18): "Helena",
    (8, 19): "Ludvík",
    (8, 20): "Bernard",
    (8, 21): "Johana",
    (8, 22): "Bohuslav",
    (8, 23): "Sandra",
    (8, 24): "Bartoloměj",
    (8, 25): "Radim",
    (8, 26): "Luděk",
    (8, 27): "Otakar",
    (8, 28): "Augustýn",
    (8, 29): "Evelína",
    (8, 30): "Vladěna",
    (8, 31): "Pavlína",
    (9, 1): "Linda, Samuel",
    (9, 2): "Adéla",
    (9, 3): "Bronislav",
    (9, 4): "Jindřiška",
    (9, 5): "Boris",
    (9, 6): "Boleslav",
    (9, 7): "Regína",
    (9, 8): "Mariana",
    (9, 9): "Daniela",
    (9, 10): "Irma",
    (9, 11): "Denisa",
    (9, 12): "Marie",
    (9, 13): "Lubor",
    (9, 14): "Radka",
    (9, 15): "Jolana",
    (9, 16): "Ludmila",
    (9, 17): "Naděžda",
    (9, 18): "Kryštof",
    (9, 19): "Zita",
    (9, 20): "Oleg",
    (9, 21): "Matouš",
    (9, 22): "Darina",
    (9, 23): "Berta",
    (9, 24): "Jaromír",
    (9, 25): "Zlata",
    (9, 26): "Andrea",
    (9, 27): "Jonáš",
    (9, 28): "Václav",
    (9, 29): "Michal",
    (9, 30): "Jeroným",
    (10, 1): "Igor",
    (10, 2): "Olivie, Oliver",
    (10, 3): "Bohumil",
    (10, 4): "František",
    (10, 5): "Eliška",
    (10, 6): "Hanuš",
    (10, 7): "Justýna",
    (10, 8): "Věra",
    (10, 9): "Štefan, Sára",
    (10, 10): "Marina",
    (10, 11): "Andrej",
    (10, 12): "Marcel",
    (10, 13): "Renáta",
    (10, 14): "Agáta",
    (10, 15): "Tereza",
    (10, 16): "Havel",
    (10, 17): "Hedvika",
    (10, 18): "Lukáš",
    (10, 19): "Michaela",
    (10, 20): "Vendelín",
    (10, 21): "Brigita",
    (10, 22): "Sabina",
    (10, 23): "Teodor",
    (10, 24): "Nina",
    (10, 25): "Beáta",
    (10, 26): "Erik",
    (10, 27): "Šarlota, Zoe",
    (10, 28): "Den vzniku Československa",
    (10, 29): "Silvie",
    (10, 30): "Tadeáš",
    (10, 31): "Štěpánka",
    (11, 1): "Felix",
    (11, 2): "Památka zesnulých",
    (11, 3): "Hubert",
    (11, 4): "Karel",
    (11, 5): "Miriam",
    (11, 6): "Liběna",
    (11, 7): "Saskie",
    (11, 8): "Bohumír",
    (11, 9): "Bohdan",
    (11, 10): "Evžen",
    (11, 11): "Martin",
    (11, 12): "Benedikt",
    (11, 13): "Tibor",
    (11, 14): "Sáva",
    (11, 15): "Leopold",
    (11, 16): "Otmar",
    (11, 17): "Mahulena",
    (11, 18): "Romana",
    (11, 19): "Alžběta",
    (11, 20): "Nikola",
    (11, 21): "Albert",
    (11, 22): "Cecílie",
    (11, 23): "Klement",
    (11, 24): "Emílie",
    (11, 25): "Kateřina",
    (11, 26): "Artur",
    (11, 27): "Xenie",
    (11, 28): "René",
    (11, 29): "Zina",
    (11, 30): "Ondřej",
    (12, 1): "Iva",
    (12, 2): "Blanka",
    (12, 3): "Svatoslav",
    (12, 4): "Barbora",
    (12, 5): "Jitka",
    (12, 6): "Mikuláš",
    (12, 7): "Benjamín, Ambrož",
    (12, 8): "Květoslava",
    (12, 9): "Vratislav",
    (12, 10): "Julie",
    (12, 11): "Dana",
    (12, 12): "Simona",
    (12, 13): "Lucie",
    (12, 14): "Lýdie",
    (12, 15): "Radana",
    (12, 16): "Albína",
    (12, 17): "Daniel",
    (12, 18): "Miloslav",
    (12, 19): "Ester",
    (12, 20): "Dagmar",
    (12, 21): "Natálie",
    (12, 22): "Šimon",
    (12, 23): "Vlasta",
    (12, 24): "Adam a Eva",
    (12, 25): "1. svátek vánoční",
    (12, 26): "Štěpán",
    (12, 27): "Žaneta",
    (12, 28): "Bohumila",
    (12, 29): "Judita",
    (12, 30): "David",
    (12, 31): "Silvestr",
}

# Moon phase names
MOON_PHASES_CS: Final = {
    "new_moon": "Nov",
    "waxing_crescent": "Dorůstající srpek",
    "first_quarter": "První čtvrť",
    "waxing_gibbous": "Dorůstající měsíc",
    "full_moon": "Úplněk",
    "waning_gibbous": "Couvající měsíc",
    "last_quarter": "Poslední čtvrť",
    "waning_crescent": "Couvající srpek",
}

MOON_PHASES_EN: Final = {
    "new_moon": "New Moon",
    "waxing_crescent": "Waxing Crescent",
    "first_quarter": "First Quarter",
    "waxing_gibbous": "Waxing Gibbous",
    "full_moon": "Full Moon",
    "waning_gibbous": "Waning Gibbous",
    "last_quarter": "Last Quarter",
    "waning_crescent": "Waning Crescent",
}

MOON_PHASE_ICONS: Final = {
    "new_moon": "mdi:moon-new",
    "waxing_crescent": "mdi:moon-waxing-crescent",
    "first_quarter": "mdi:moon-first-quarter",
    "waxing_gibbous": "mdi:moon-waxing-gibbous",
    "full_moon": "mdi:moon-full",
    "waning_gibbous": "mdi:moon-waning-gibbous",
    "last_quarter": "mdi:moon-last-quarter",
    "waning_crescent": "mdi:moon-waning-crescent",
}

# Seasons
SEASONS_CS: Final = {
    "spring": "Jaro",
    "summer": "Léto",
    "autumn": "Podzim",
    "winter": "Zima",
}

SEASONS_EN: Final = {
    "spring": "Spring",
    "summer": "Summer",
    "autumn": "Autumn",
    "winter": "Winter",
}

SEASON_ICONS: Final = {
    "spring": "mdi:flower",
    "summer": "mdi:white-balance-sunny",
    "autumn": "mdi:leaf",
    "winter": "mdi:snowflake",
}

# Zodiac signs with date ranges (month, day) start and end
ZODIAC_SIGNS: Final = {
    "aries": ((3, 21), (4, 19)),
    "taurus": ((4, 20), (5, 20)),
    "gemini": ((5, 21), (6, 20)),
    "cancer": ((6, 21), (7, 22)),
    "leo": ((7, 23), (8, 22)),
    "virgo": ((8, 23), (9, 22)),
    "libra": ((9, 23), (10, 22)),
    "scorpio": ((10, 23), (11, 21)),
    "sagittarius": ((11, 22), (12, 21)),
    "capricorn": ((12, 22), (1, 19)),
    "aquarius": ((1, 20), (2, 18)),
    "pisces": ((2, 19), (3, 20)),
}

ZODIAC_CS: Final = {
    "aries": "Beran",
    "taurus": "Býk",
    "gemini": "Blíženci",
    "cancer": "Rak",
    "leo": "Lev",
    "virgo": "Panna",
    "libra": "Váhy",
    "scorpio": "Štír",
    "sagittarius": "Střelec",
    "capricorn": "Kozoroh",
    "aquarius": "Vodnář",
    "pisces": "Ryby",
}

ZODIAC_EN: Final = {
    "aries": "Aries",
    "taurus": "Taurus",
    "gemini": "Gemini",
    "cancer": "Cancer",
    "leo": "Leo",
    "virgo": "Virgo",
    "libra": "Libra",
    "scorpio": "Scorpio",
    "sagittarius": "Sagittarius",
    "capricorn": "Capricorn",
    "aquarius": "Aquarius",
    "pisces": "Pisces",
}

ZODIAC_ICONS: Final = {
    "aries": "mdi:zodiac-aries",
    "taurus": "mdi:zodiac-taurus",
    "gemini": "mdi:zodiac-gemini",
    "cancer": "mdi:zodiac-cancer",
    "leo": "mdi:zodiac-leo",
    "virgo": "mdi:zodiac-virgo",
    "libra": "mdi:zodiac-libra",
    "scorpio": "mdi:zodiac-scorpio",
    "sagittarius": "mdi:zodiac-sagittarius",
    "capricorn": "mdi:zodiac-capricorn",
    "aquarius": "mdi:zodiac-aquarius",
    "pisces": "mdi:zodiac-pisces",
}

# Default sensors to enable
DEFAULT_SENSORS: Final = [
    SENSOR_DATE,
    SENSOR_DAY_NAME,
    SENSOR_WEEK_NUMBER,
]

# Update interval (in minutes)
UPDATE_INTERVAL: Final = 1
