"""Constants for Datum Display integration."""
from typing import Final

DOMAIN: Final = "datum_display"
CONF_LANGUAGE: Final = "language"
CONF_DATE_FORMAT: Final = "date_format"
CONF_SENSORS: Final = "sensors"

# Available languages
LANGUAGE_CS: Final = "cs"
LANGUAGE_EN: Final = "en"

LANGUAGES: Final = {
    LANGUAGE_CS: "Čeština",
    LANGUAGE_EN: "English",
}

# Date format identifiers
FORMAT_DD_MM_YYYY_DOT: Final = "dd.mm.yyyy"
FORMAT_DD_MM_YYYY_DOT_SPACE: Final = "dd. mm. yyyy"
FORMAT_D_M_YYYY_DOT: Final = "d.m.yyyy"
FORMAT_DD_MM_YYYY_SLASH: Final = "dd/mm/yyyy"
FORMAT_MM_DD_YYYY_SLASH: Final = "mm/dd/yyyy"
FORMAT_YYYY_MM_DD: Final = "yyyy-mm-dd"
FORMAT_DD_MONTH_YYYY: Final = "dd_month_yyyy"
FORMAT_DAY_DD_MONTH_YYYY: Final = "day_dd_month_yyyy"
FORMAT_DAY_DD_MONTH: Final = "day_dd_month"
FORMAT_DD_MONTH: Final = "dd_month"
FORMAT_DAY_SHORT_DD_MM: Final = "day_short_dd_mm"
FORMAT_DAY_ABBR_DD_MM: Final = "day_abbr_dd_mm"
FORMAT_ISO8601: Final = "iso8601"
FORMAT_RELATIVE: Final = "relative"
FORMAT_VERBAL: Final = "verbal"

DATE_FORMATS: Final = {
    FORMAT_DD_MM_YYYY_DOT: "DD.MM.YYYY",
    FORMAT_DD_MM_YYYY_DOT_SPACE: "DD. MM. YYYY",
    FORMAT_D_M_YYYY_DOT: "D.M.YYYY",
    FORMAT_DD_MM_YYYY_SLASH: "DD/MM/YYYY",
    FORMAT_MM_DD_YYYY_SLASH: "MM/DD/YYYY",
    FORMAT_YYYY_MM_DD: "YYYY-MM-DD",
    FORMAT_DD_MONTH_YYYY: "DD. měsíc YYYY",
    FORMAT_DAY_DD_MONTH_YYYY: "Den DD. měsíc YYYY",
    FORMAT_DAY_DD_MONTH: "Den DD. měsíc",
    FORMAT_DD_MONTH: "DD měsíc",
    FORMAT_DAY_SHORT_DD_MM: "Den, DD.MM.",
    FORMAT_DAY_ABBR_DD_MM: "Zkr. den DD.MM.",
    FORMAT_ISO8601: "ISO 8601",
    FORMAT_RELATIVE: "Relativní (Dnes/Včera...)",
    FORMAT_VERBAL: "Slovní",
}

# Sensor types
SENSOR_DATE: Final = "date"
SENSOR_DAY_NAME: Final = "day_name"
SENSOR_DAY_NAME_SHORT: Final = "day_name_short"
SENSOR_WEEK_NUMBER: Final = "week_number"
SENSOR_MONTH_NAME: Final = "month_name"
SENSOR_MONTH_NUMBER: Final = "month_number"
SENSOR_YEAR: Final = "year"
SENSOR_DAY_OF_YEAR: Final = "day_of_year"
SENSOR_DAYS_IN_MONTH: Final = "days_in_month"
SENSOR_IS_LEAP_YEAR: Final = "is_leap_year"
SENSOR_QUARTER: Final = "quarter"
SENSOR_DAYS_UNTIL_END_OF_YEAR: Final = "days_until_end_of_year"
SENSOR_WEEK_DATES: Final = "week_dates"
SENSOR_TOMORROW: Final = "tomorrow"
SENSOR_YESTERDAY: Final = "yesterday"
SENSOR_WEEK_START: Final = "week_start"
SENSOR_WEEK_END: Final = "week_end"
SENSOR_HOLIDAY: Final = "holiday"
SENSOR_NAME_DAY: Final = "name_day"
SENSOR_IS_WORKDAY: Final = "is_workday"
SENSOR_MOON_PHASE: Final = "moon_phase"
SENSOR_SEASON: Final = "season"
SENSOR_ZODIAC: Final = "zodiac"
SENSOR_DAYS_UNTIL_CHRISTMAS: Final = "days_until_christmas"
SENSOR_DAYS_UNTIL_NEW_YEAR: Final = "days_until_new_year"
SENSOR_DAYS_UNTIL_EASTER: Final = "days_until_easter"
SENSOR_WORKDAYS_IN_MONTH: Final = "workdays_in_month"
SENSOR_WORKDAYS_LEFT: Final = "workdays_left"
SENSOR_HOLIDAY_DE: Final = "holiday_de"
SENSOR_HOLIDAY_SK: Final = "holiday_sk"
SENSOR_NAME_DAY_SK: Final = "name_day_sk"
SENSOR_NAME_DAY_DE: Final = "name_day_de"

SENSOR_TYPES: Final = {
    SENSOR_DATE: "Datum",
    SENSOR_DAY_NAME: "Název dne",
    SENSOR_DAY_NAME_SHORT: "Zkrácený název dne",
    SENSOR_WEEK_NUMBER: "Číslo týdne",
    SENSOR_MONTH_NAME: "Název měsíce",
    SENSOR_MONTH_NUMBER: "Číslo měsíce",
    SENSOR_YEAR: "Rok",
    SENSOR_DAY_OF_YEAR: "Den v roce",
    SENSOR_DAYS_IN_MONTH: "Počet dnů v měsíci",
    SENSOR_IS_LEAP_YEAR: "Přestupný rok",
    SENSOR_QUARTER: "Čtvrtletí",
    SENSOR_DAYS_UNTIL_END_OF_YEAR: "Dnů do konce roku",
    SENSOR_WEEK_DATES: "Data týdne",
    SENSOR_TOMORROW: "Zítra",
    SENSOR_YESTERDAY: "Včera",
    SENSOR_WEEK_START: "Začátek týdne",
    SENSOR_WEEK_END: "Konec týdne",
    SENSOR_HOLIDAY: "Svátek",
    SENSOR_NAME_DAY: "Jmeniny",
    SENSOR_IS_WORKDAY: "Pracovní den",
    SENSOR_MOON_PHASE: "Fáze měsíce",
    SENSOR_SEASON: "Roční období",
    SENSOR_ZODIAC: "Znamení zvěrokruhu",
    SENSOR_DAYS_UNTIL_CHRISTMAS: "Dnů do Vánoc",
    SENSOR_DAYS_UNTIL_NEW_YEAR: "Dnů do Nového roku",
    SENSOR_DAYS_UNTIL_EASTER: "Dnů do Velikonoc",
    SENSOR_WORKDAYS_IN_MONTH: "Pracovních dnů v měsíci",
    SENSOR_WORKDAYS_LEFT: "Zbývá pracovních dnů",
    SENSOR_HOLIDAY_DE: "Německý svátek",
    SENSOR_HOLIDAY_SK: "Slovenský svátek",
    SENSOR_NAME_DAY_SK: "Slovenské meniny",
    SENSOR_NAME_DAY_DE: "Německé jmeniny",
}

# Czech day names
DAYS_CS: Final = {
    0: "Pondělí",
    1: "Úterý",
    2: "Středa",
    3: "Čtvrtek",
    4: "Pátek",
    5: "Sobota",
    6: "Neděle",
}

DAYS_CS_SHORT: Final = {
    0: "Po",
    1: "Út",
    2: "St",
    3: "Čt",
    4: "Pá",
    5: "So",
    6: "Ne",
}

# English day names
DAYS_EN: Final = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}

DAYS_EN_SHORT: Final = {
    0: "Mon",
    1: "Tue",
    2: "Wed",
    3: "Thu",
    4: "Fri",
    5: "Sat",
    6: "Sun",
}

# Czech month names (nominative)
MONTHS_CS: Final = {
    1: "Leden",
    2: "Únor",
    3: "Březen",
    4: "Duben",
    5: "Květen",
    6: "Červen",
    7: "Červenec",
    8: "Srpen",
    9: "Září",
    10: "Říjen",
    11: "Listopad",
    12: "Prosinec",
}

# Czech month names (genitive - for dates like "25. ledna")
MONTHS_CS_GENITIVE: Final = {
    1: "ledna",
    2: "února",
    3: "března",
    4: "dubna",
    5: "května",
    6: "června",
    7: "července",
    8: "srpna",
    9: "září",
    10: "října",
    11: "listopadu",
    12: "prosince",
}

# English month names
MONTHS_EN: Final = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
}

# Relative date translations
RELATIVE_CS: Final = {
    -2: "Předevčírem",
    -1: "Včera",
    0: "Dnes",
    1: "Zítra",
    2: "Pozítří",
}

RELATIVE_EN: Final = {
    -2: "Day before yesterday",
    -1: "Yesterday",
    0: "Today",
    1: "Tomorrow",
    2: "Day after tomorrow",
}

# Czech ordinal numbers for verbal dates (1-31)
ORDINALS_CS: Final = {
    1: "Prvního",
    2: "Druhého",
    3: "Třetího",
    4: "Čtvrtého",
    5: "Pátého",
    6: "Šestého",
    7: "Sedmého",
    8: "Osmého",
    9: "Devátého",
    10: "Desátého",
    11: "Jedenáctého",
    12: "Dvanáctého",
    13: "Třináctého",
    14: "Čtrnáctého",
    15: "Patnáctého",
    16: "Šestnáctého",
    17: "Sedmnáctého",
    18: "Osmnáctého",
    19: "Devatenáctého",
    20: "Dvacátého",
    21: "Dvacátého prvního",
    22: "Dvacátého druhého",
    23: "Dvacátého třetího",
    24: "Dvacátého čtvrtého",
    25: "Dvacátého pátého",
    26: "Dvacátého šestého",
    27: "Dvacátého sedmého",
    28: "Dvacátého osmého",
    29: "Dvacátého devátého",
    30: "Třicátého",
    31: "Třicátého prvního",
}

# English ordinal numbers for verbal dates (1-31)
ORDINALS_EN: Final = {
    1: "First",
    2: "Second",
    3: "Third",
    4: "Fourth",
    5: "Fifth",
    6: "Sixth",
    7: "Seventh",
    8: "Eighth",
    9: "Ninth",
    10: "Tenth",
    11: "Eleventh",
    12: "Twelfth",
    13: "Thirteenth",
    14: "Fourteenth",
    15: "Fifteenth",
    16: "Sixteenth",
    17: "Seventeenth",
    18: "Eighteenth",
    19: "Nineteenth",
    20: "Twentieth",
    21: "Twenty-first",
    22: "Twenty-second",
    23: "Twenty-third",
    24: "Twenty-fourth",
    25: "Twenty-fifth",
    26: "Twenty-sixth",
    27: "Twenty-seventh",
    28: "Twenty-eighth",
    29: "Twenty-ninth",
    30: "Thirtieth",
    31: "Thirty-first",
}

# Czech state holidays (month, day): name
HOLIDAYS_CS: Final = {
    (1, 1): "Nový rok / Den obnovy samostatného českého státu",
    (5, 1): "Svátek práce",
    (5, 8): "Den vítězství",
    (7, 5): "Den slovanských věrozvěstů Cyrila a Metoděje",
    (7, 6): "Den upálení mistra Jana Husa",
    (9, 28): "Den české státnosti",
    (10, 28): "Den vzniku samostatného československého státu",
    (11, 17): "Den boje za svobodu a demokracii",
    (12, 24): "Štědrý den",
    (12, 25): "1. svátek vánoční",
    (12, 26): "2. svátek vánoční",
}

# English holidays
HOLIDAYS_EN: Final = {
    (1, 1): "New Year's Day",
    (5, 1): "Labour Day",
    (5, 8): "Victory Day",
    (7, 5): "Saints Cyril and Methodius Day",
    (7, 6): "Jan Hus Day",
    (9, 28): "Czech Statehood Day",
    (10, 28): "Czechoslovak Independence Day",
    (11, 17): "Struggle for Freedom and Democracy Day",
    (12, 24): "Christmas Eve",
    (12, 25): "Christmas Day",
    (12, 26): "St. Stephen's Day",
}

# German holidays (federal, some vary by state)
HOLIDAYS_DE: Final = {
    (1, 1): "Neujahr",
    (1, 6): "Heilige Drei Könige",
    (5, 1): "Tag der Arbeit",
    (8, 15): "Mariä Himmelfahrt",
    (10, 3): "Tag der Deutschen Einheit",
    (10, 31): "Reformationstag",
    (11, 1): "Allerheiligen",
    (12, 24): "Heiligabend",
    (12, 25): "1. Weihnachtstag",
    (12, 26): "2. Weihnachtstag",
    (12, 31): "Silvester",
}

# German name days (Namenstage)
NAME_DAYS_DE: Final = {
    (1, 1): "Maria",
    (1, 2): "Basilius, Gregor",
    (1, 3): "Genoveva, Odilo",
    (1, 4): "Angelika, Roger",
    (1, 5): "Emilia, Johann",
    (1, 6): "Kaspar, Melchior, Balthasar",
    (1, 7): "Reinhold, Valentin",
    (1, 8): "Erhard, Gudula",
    (1, 9): "Adrian, Julian",
    (1, 10): "Gregor, Paul",
    (1, 11): "Thomas",
    (1, 12): "Ernst, Tatjana",
    (1, 13): "Hilarius, Jutta",
    (1, 14): "Felix, Rainer",
    (1, 15): "Arnold, Mauro",
    (1, 16): "Marcel, Ulrich",
    (1, 17): "Anton, Beatrix",
    (1, 18): "Regina, Wolfrid",
    (1, 19): "Heinrich, Pia",
    (1, 20): "Fabian, Sebastian",
    (1, 21): "Agnes, Meinrad",
    (1, 22): "Vinzenz, Walter",
    (1, 23): "Heinrich, Hartmut",
    (1, 24): "Franz von Sales",
    (1, 25): "Pauli Bekehrung",
    (1, 26): "Paula, Timotheus",
    (1, 27): "Angela, Julian",
    (1, 28): "Karl, Thomas",
    (1, 29): "Josef, Valerius",
    (1, 30): "Martina, Adelgunde",
    (1, 31): "Johannes Bosco",
    (2, 1): "Brigitta, Severus",
    (2, 2): "Maria Lichtmess",
    (2, 3): "Blasius, Oskar",
    (2, 4): "Veronika, Gilbert",
    (2, 5): "Agatha, Albuin",
    (2, 6): "Dorothea, Paul",
    (2, 7): "Richard, Romuald",
    (2, 8): "Hieronymus, Elfriede",
    (2, 9): "Apollonia, Anna",
    (2, 10): "Bruno, Scholastika",
    (2, 11): "Theodora, Benedikt",
    (2, 12): "Eulalia, Reginald",
    (2, 13): "Adolf, Gisela",
    (2, 14): "Valentin, Cyrill",
    (2, 15): "Siegfried, Georgia",
    (2, 16): "Juliana, Pamela",
    (2, 17): "Alexis, Benignus",
    (2, 18): "Konstanze, Simon",
    (2, 19): "Bonifatius, Irmgard",
    (2, 20): "Amata, Corona",
    (2, 21): "Gunhild, Peter",
    (2, 22): "Isabella, Petri",
    (2, 23): "Polykarp, Romana",
    (2, 24): "Matthias",
    (2, 25): "Walburga",
    (2, 26): "Alexander, Ottokar",
    (2, 27): "Gabriel, Marko",
    (2, 28): "Roman, Silvana",
    (2, 29): "Oswald",
    (3, 1): "Albin, David",
    (3, 2): "Agnes, Karl",
    (3, 3): "Friedrich, Kunigunde",
    (3, 4): "Kasimir, Humbert",
    (3, 5): "Dietmar, Olivia",
    (3, 6): "Fridolin, Colette",
    (3, 7): "Felicitas, Reinhard",
    (3, 8): "Johannes, Philemon",
    (3, 9): "Bruno, Franziska",
    (3, 10): "Gustav, Emil",
    (3, 11): "Rosina, Alram",
    (3, 12): "Almut, Gregor",
    (3, 13): "Judith, Paulina",
    (3, 14): "Mathilde, Eva",
    (3, 15): "Klemens, Luise",
    (3, 16): "Heribert, Herbert",
    (3, 17): "Gertrud, Patrick",
    (3, 18): "Eduard, Cyrill",
    (3, 19): "Josef",
    (3, 20): "Claudia, Wolfram",
    (3, 21): "Benedikt, Christian",
    (3, 22): "Lea, Elmar",
    (3, 23): "Eberhard, Otto",
    (3, 24): "Elias, Karin",
    (3, 25): "Mariä Verkündigung",
    (3, 26): "Ludger, Emanuel",
    (3, 27): "Augusta, Frowin",
    (3, 28): "Guntram, Ingbert",
    (3, 29): "Helmut, Ludolf",
    (3, 30): "Amadeus, Dieter",
    (3, 31): "Cornelia, Benjamin",
    (4, 1): "Hugo, Irene",
    (4, 2): "Franz von Paola",
    (4, 3): "Richard",
    (4, 4): "Isidor, Konrad",
    (4, 5): "Vinzenz Ferrer",
    (4, 6): "Wilhelm, Sixtus",
    (4, 7): "Hermann, Johann",
    (4, 8): "Walter, Beate",
    (4, 9): "Waltraud, Hugo",
    (4, 10): "Engelbert, Holger",
    (4, 11): "Stanislaus, Hildebrand",
    (4, 12): "Julius, Herta",
    (4, 13): "Martin, Ida",
    (4, 14): "Ernestine, Lidwina",
    (4, 15): "Anastasia, Damian",
    (4, 16): "Bernadette, Magnus",
    (4, 17): "Rudolf, Eberhard",
    (4, 18): "Werner, Wigbert",
    (4, 19): "Emma, Gerold",
    (4, 20): "Odette, Hildegund",
    (4, 21): "Anselm, Konrad",
    (4, 22): "Kajus, Leonidas",
    (4, 23): "Georg, Adalbert",
    (4, 24): "Wilfried, Marian",
    (4, 25): "Markus",
    (4, 26): "Helene, Trudpert",
    (4, 27): "Petrus, Zita",
    (4, 28): "Hugo, Ludwig",
    (4, 29): "Katharina von Siena",
    (4, 30): "Pius, Pauline",
    (5, 1): "Josef der Arbeiter",
    (5, 2): "Sigismund, Boris",
    (5, 3): "Philipp, Jakob",
    (5, 4): "Florian, Guido",
    (5, 5): "Gotthard, Sigrid",
    (5, 6): "Gundula, Valeria",
    (5, 7): "Gisela, Helga",
    (5, 8): "Ulrike, Ida",
    (5, 9): "Beat, Volkmar",
    (5, 10): "Gordian, Isidor",
    (5, 11): "Mamertus, Gangolf",
    (5, 12): "Pankratius, Imelda",
    (5, 13): "Servatius, Rolanda",
    (5, 14): "Bonifatius, Corona",
    (5, 15): "Sophie, Isidor",
    (5, 16): "Johannes, Ubald",
    (5, 17): "Pascal, Bruno",
    (5, 18): "Erich, Johannes",
    (5, 19): "Ivo, Kuno",
    (5, 20): "Bernhardin, Elfriede",
    (5, 21): "Hermann, Wiltrud",
    (5, 22): "Julia, Rita",
    (5, 23): "Renate, Désirée",
    (5, 24): "Dagmar, Esther",
    (5, 25): "Beda, Urban",
    (5, 26): "Philipp Neri",
    (5, 27): "Augustin, Bruno",
    (5, 28): "German, Wilhelm",
    (5, 29): "Maximin, Irmtraud",
    (5, 30): "Ferdinand, Johanna",
    (5, 31): "Mariä Heimsuchung",
    (6, 1): "Justin, Simeon",
    (6, 2): "Armin, Erasmus",
    (6, 3): "Karl, Monika",
    (6, 4): "Christa, Eva",
    (6, 5): "Bonifatius, Winfried",
    (6, 6): "Norbert, Bertrand",
    (6, 7): "Robert, Gottlieb",
    (6, 8): "Medard, Helga",
    (6, 9): "Ephrem, Gratia",
    (6, 10): "Heinrich, Diana",
    (6, 11): "Barnabas, Paula",
    (6, 12): "Leo, Guido",
    (6, 13): "Antonius von Padua",
    (6, 14): "Gottschalk, Hartwig",
    (6, 15): "Vitus, Lothar",
    (6, 16): "Benno, Luitgard",
    (6, 17): "Adolf, Volker",
    (6, 18): "Elisabeth, Marina",
    (6, 19): "Romuald, Juliana",
    (6, 20): "Adalbert, Florentina",
    (6, 21): "Alois, Alban",
    (6, 22): "Thomas More",
    (6, 23): "Edeltraud, Maria",
    (6, 24): "Johannes der Täufer",
    (6, 25): "Dorothea, Eleonore",
    (6, 26): "David, Johann",
    (6, 27): "Hemma, Harald",
    (6, 28): "Irenäus, Ekkehard",
    (6, 29): "Peter und Paul",
    (6, 30): "Otto, Bertram",
    (7, 1): "Theobald, Aaron",
    (7, 2): "Mariä Heimsuchung",
    (7, 3): "Thomas",
    (7, 4): "Ulrich, Elisabeth",
    (7, 5): "Albrecht, Letizia",
    (7, 6): "Maria Goretti",
    (7, 7): "Willibald, Edda",
    (7, 8): "Kilian, Edgar",
    (7, 9): "Veronika, Hermine",
    (7, 10): "Knud, Engelbert",
    (7, 11): "Benedikt, Oliver",
    (7, 12): "Henriette, Siegbert",
    (7, 13): "Heinrich, Sara",
    (7, 14): "Camillus, Roland",
    (7, 15): "Bonaventura, Egon",
    (7, 16): "Carmen, Elvira",
    (7, 17): "Gabriela, Charlotte",
    (7, 18): "Arnulf, Friedrich",
    (7, 19): "Marina, Reto",
    (7, 20): "Margareta, Elias",
    (7, 21): "Daniel, Julia",
    (7, 22): "Maria Magdalena",
    (7, 23): "Birgitta, Liborius",
    (7, 24): "Christoph, Luise",
    (7, 25): "Jakob, Valentina",
    (7, 26): "Anna, Joachim",
    (7, 27): "Berthold, Natalie",
    (7, 28): "Adele, Benno",
    (7, 29): "Martha, Olaf",
    (7, 30): "Ingeborg, Petrus",
    (7, 31): "Ignatius von Loyola",
    (8, 1): "Alfons",
    (8, 2): "Eusebius, Julian",
    (8, 3): "Lydia, August",
    (8, 4): "Johannes Maria Vianney",
    (8, 5): "Oswald, Maria",
    (8, 6): "Verklärung Christi",
    (8, 7): "Afra, Albert",
    (8, 8): "Dominikus, Cyriak",
    (8, 9): "Edith Stein",
    (8, 10): "Laurentius, Astrid",
    (8, 11): "Klara, Susanna",
    (8, 12): "Hilaria, Karl",
    (8, 13): "Hippolyt, Marco",
    (8, 14): "Maximilian Kolbe",
    (8, 15): "Mariä Himmelfahrt",
    (8, 16): "Stephan, Rochus",
    (8, 17): "Hyazinth, Clara",
    (8, 18): "Helena, Claudia",
    (8, 19): "Sebald, Julius",
    (8, 20): "Bernhard, Samuel",
    (8, 21): "Pius, Linda",
    (8, 22): "Regina, Sigfrid",
    (8, 23): "Rosa, Zachäus",
    (8, 24): "Bartholomäus",
    (8, 25): "Ludwig, Patricia",
    (8, 26): "Miriam, Teresa",
    (8, 27): "Monika, Gebhard",
    (8, 28): "Augustinus, Adelinde",
    (8, 29): "Johannes Enthauptung",
    (8, 30): "Felix, Heribert",
    (8, 31): "Raimund, Paulinus",
    (9, 1): "Ägidius, Ruth",
    (9, 2): "Ingrid, Franz",
    (9, 3): "Gregor, Sophie",
    (9, 4): "Rosalia, Ida",
    (9, 5): "Roswitha, Hermine",
    (9, 6): "Magnus, Gundolf",
    (9, 7): "Regina, Ralph",
    (9, 8): "Mariä Geburt",
    (9, 9): "Otmar, Pedro",
    (9, 10): "Diethard, Nikolaus",
    (9, 11): "Felix, Regula",
    (9, 12): "Mariä Namen",
    (9, 13): "Tobias, Notburga",
    (9, 14): "Kreuzerhöhung",
    (9, 15): "Dolores, Melitta",
    (9, 16): "Cornelius, Cyprian",
    (9, 17): "Hildegard, Lambert",
    (9, 18): "Josef von Copertino",
    (9, 19): "Januarius, Thorsten",
    (9, 20): "Eustachius, Susanna",
    (9, 21): "Matthäus, Jonas",
    (9, 22): "Moritz, Emmeram",
    (9, 23): "Thekla, Linus",
    (9, 24): "Rupert, Virgil",
    (9, 25): "Klaus, Wigand",
    (9, 26): "Kosmas, Damian",
    (9, 27): "Vinzenz von Paul",
    (9, 28): "Wenzel, Lioba",
    (9, 29): "Michael, Gabriel, Raphael",
    (9, 30): "Hieronymus, Urs",
    (10, 1): "Theresia vom Kinde Jesu",
    (10, 2): "Schutzengelfest",
    (10, 3): "Ewald, Udo",
    (10, 4): "Franz von Assisi",
    (10, 5): "Herwig, Gallina",
    (10, 6): "Bruno, Adalbero",
    (10, 7): "Rosa von Lima",
    (10, 8): "Simeon, Günther",
    (10, 9): "Dionys, Sara",
    (10, 10): "Gereon, Viktor",
    (10, 11): "Bruno, Alexander",
    (10, 12): "Maximilian, Horst",
    (10, 13): "Eduard, Koloman",
    (10, 14): "Burkhard, Kallistus",
    (10, 15): "Theresia von Avila",
    (10, 16): "Hedwig, Gallus",
    (10, 17): "Ignatius von Antiochien",
    (10, 18): "Lukas",
    (10, 19): "Frieda, Paul vom Kreuz",
    (10, 20): "Wendelin, Vitalis",
    (10, 21): "Ursula, Celina",
    (10, 22): "Cordula, Salome",
    (10, 23): "Johannes von Capestrano",
    (10, 24): "Anton Maria Claret",
    (10, 25): "Krispin, Daria",
    (10, 26): "Amandus, Wieland",
    (10, 27): "Sabina, Wolfhard",
    (10, 28): "Simon, Judas",
    (10, 29): "Ermelinde, Narzissus",
    (10, 30): "Alfons Rodriguez",
    (10, 31): "Wolfgang, Christoph",
    (11, 1): "Allerheiligen",
    (11, 2): "Allerseelen",
    (11, 3): "Hubert, Pirmin",
    (11, 4): "Karl Borromäus",
    (11, 5): "Emmerich, Bernhard",
    (11, 6): "Leonhard",
    (11, 7): "Engelbert, Carina",
    (11, 8): "Gottfried, Willehad",
    (11, 9): "Theodor, Herfried",
    (11, 10): "Leo, Andreas",
    (11, 11): "Martin",
    (11, 12): "Kunibert, Josaphat",
    (11, 13): "Stanislaus, Eugen",
    (11, 14): "Bernhard, Sidonia",
    (11, 15): "Leopold, Albert",
    (11, 16): "Margareta, Othmar",
    (11, 17): "Gertrud, Hilda",
    (11, 18): "Odo, Roman",
    (11, 19): "Elisabeth",
    (11, 20): "Edmund, Korbinian",
    (11, 21): "Gelasius",
    (11, 22): "Cäcilia",
    (11, 23): "Klemens, Felicitas",
    (11, 24): "Flora, Albert",
    (11, 25): "Katharina",
    (11, 26): "Konrad, Kurt",
    (11, 27): "Brunhilde, Oda",
    (11, 28): "Gunther, Berta",
    (11, 29): "Friedrich, Buchard",
    (11, 30): "Andreas",
    (12, 1): "Blanka, Natalie",
    (12, 2): "Bibiana, Lucius",
    (12, 3): "Franz Xaver",
    (12, 4): "Barbara, Johannes",
    (12, 5): "Gerald, Reinhard",
    (12, 6): "Nikolaus",
    (12, 7): "Ambros, Farah",
    (12, 8): "Mariä Empfängnis",
    (12, 9): "Valeria, Liborius",
    (12, 10): "Angelina, Bruno",
    (12, 11): "Damasus, Arthur",
    (12, 12): "Johanna, Hartmann",
    (12, 13): "Lucia, Ottilie",
    (12, 14): "Johannes vom Kreuz",
    (12, 15): "Christiane, Nina",
    (12, 16): "Adelheid, Albina",
    (12, 17): "Lazarus, Jolanda",
    (12, 18): "Gratian, Wunibald",
    (12, 19): "Konrad, Urban",
    (12, 20): "Holger, Julius",
    (12, 21): "Thomas",
    (12, 22): "Jutta, Franziska",
    (12, 23): "Viktoria, Johannes",
    (12, 24): "Adam und Eva",
    (12, 25): "Weihnachten",
    (12, 26): "Stephan",
    (12, 27): "Johannes Evangelist",
    (12, 28): "Unschuldige Kinder",
    (12, 29): "David, Thomas Becket",
    (12, 30): "Felix, Sabinus",
    (12, 31): "Silvester",
}

# Slovak holidays
HOLIDAYS_SK: Final = {
    (1, 1): "Deň vzniku Slovenskej republiky",
    (1, 6): "Zjavenie Pána (Traja králi)",
    (5, 1): "Sviatok práce",
    (5, 8): "Deň víťazstva nad fašizmom",
    (7, 5): "Sviatok svätého Cyrila a Metoda",
    (8, 29): "Výročie SNP",
    (9, 1): "Deň Ústavy Slovenskej republiky",
    (9, 15): "Sedembolestná Panna Mária",
    (11, 1): "Sviatok všetkých svätých",
    (11, 17): "Deň boja za slobodu a demokraciu",
    (12, 24): "Štedrý deň",
    (12, 25): "Prvý sviatok vianočný",
    (12, 26): "Druhý sviatok vianočný",
}

# Slovak name days (meniny)
NAME_DAYS_SK: Final = {
    (1, 1): "Nový rok",
    (1, 2): "Alexandra",
    (1, 3): "Daniela",
    (1, 4): "Drahoslav",
    (1, 5): "Andrea",
    (1, 6): "Antónia",
    (1, 7): "Bohuslava",
    (1, 8): "Severín",
    (1, 9): "Alexej",
    (1, 10): "Dáša",
    (1, 11): "Malvína",
    (1, 12): "Ernest",
    (1, 13): "Rastislav",
    (1, 14): "Radovan",
    (1, 15): "Dobroslav",
    (1, 16): "Kristína",
    (1, 17): "Nataša",
    (1, 18): "Bohdana",
    (1, 19): "Drahomíra",
    (1, 20): "Dalibor",
    (1, 21): "Vincent",
    (1, 22): "Zora",
    (1, 23): "Miloš",
    (1, 24): "Timotej",
    (1, 25): "Gejza",
    (1, 26): "Tamara",
    (1, 27): "Bohuš",
    (1, 28): "Alfonz",
    (1, 29): "Gašpar",
    (1, 30): "Ema",
    (1, 31): "Emil",
    (2, 1): "Tatiana",
    (2, 2): "Erika, Erik",
    (2, 3): "Blažej",
    (2, 4): "Veronika",
    (2, 5): "Agáta",
    (2, 6): "Dorota",
    (2, 7): "Vanda",
    (2, 8): "Zoja",
    (2, 9): "Zdenko",
    (2, 10): "Gabriela",
    (2, 11): "Dezider",
    (2, 12): "Perla",
    (2, 13): "Arpád",
    (2, 14): "Valentín",
    (2, 15): "Pravoslav",
    (2, 16): "Ida",
    (2, 17): "Miloslava",
    (2, 18): "Jaromír",
    (2, 19): "Vlasta",
    (2, 20): "Lívia",
    (2, 21): "Eleonóra",
    (2, 22): "Etela",
    (2, 23): "Roman, Romana",
    (2, 24): "Matej",
    (2, 25): "Frederik, Frederika",
    (2, 26): "Viktor",
    (2, 27): "Alexander",
    (2, 28): "Zlatica",
    (2, 29): "Radomír",
    (3, 1): "Albín",
    (3, 2): "Anežka",
    (3, 3): "Bohumil, Bohumila",
    (3, 4): "Kazimír",
    (3, 5): "Fridrich",
    (3, 6): "Radoslav, Radoslava",
    (3, 7): "Tomáš",
    (3, 8): "Alan, Alana",
    (3, 9): "Františka",
    (3, 10): "Branislav, Bruno",
    (3, 11): "Angela, Angelika",
    (3, 12): "Gregor",
    (3, 13): "Vlastimil",
    (3, 14): "Matilda",
    (3, 15): "Svetlana",
    (3, 16): "Boleslav",
    (3, 17): "Ľubica",
    (3, 18): "Eduard",
    (3, 19): "Jozef",
    (3, 20): "Víťazoslav",
    (3, 21): "Blahoslav",
    (3, 22): "Beňadik",
    (3, 23): "Adrián",
    (3, 24): "Gabriel",
    (3, 25): "Marián",
    (3, 26): "Emanuel",
    (3, 27): "Alena",
    (3, 28): "Soňa",
    (3, 29): "Miroslav",
    (3, 30): "Vieroslav",
    (3, 31): "Benjamín",
    (4, 1): "Hugo",
    (4, 2): "Zita",
    (4, 3): "Richard",
    (4, 4): "Izidor",
    (4, 5): "Miroslava",
    (4, 6): "Irena",
    (4, 7): "Zoltán",
    (4, 8): "Albert",
    (4, 9): "Milena",
    (4, 10): "Igor",
    (4, 11): "Július",
    (4, 12): "Estera",
    (4, 13): "Aleš",
    (4, 14): "Justína",
    (4, 15): "Fedor",
    (4, 16): "Dana, Danica",
    (4, 17): "Rudolf",
    (4, 18): "Valér",
    (4, 19): "Jela",
    (4, 20): "Marcel",
    (4, 21): "Ervín",
    (4, 22): "Slavomír",
    (4, 23): "Vojtech",
    (4, 24): "Juraj",
    (4, 25): "Marek",
    (4, 26): "Jaroslava",
    (4, 27): "Jaroslav",
    (4, 28): "Jarmila",
    (4, 29): "Lea",
    (4, 30): "Anastázia",
    (5, 1): "Sviatok práce",
    (5, 2): "Žigmund",
    (5, 3): "Galina",
    (5, 4): "Florián",
    (5, 5): "Lesana",
    (5, 6): "Hermína",
    (5, 7): "Monika",
    (5, 8): "Ingrida",
    (5, 9): "Roland",
    (5, 10): "Viktória",
    (5, 11): "Blažena",
    (5, 12): "Pankrác",
    (5, 13): "Servác",
    (5, 14): "Bonifác",
    (5, 15): "Žofia",
    (5, 16): "Svetozár",
    (5, 17): "Gizela",
    (5, 18): "Viola",
    (5, 19): "Gertrúda",
    (5, 20): "Bernard",
    (5, 21): "Zina",
    (5, 22): "Júlia, Juliana",
    (5, 23): "Želmíra",
    (5, 24): "Ela",
    (5, 25): "Urban",
    (5, 26): "Dušan",
    (5, 27): "Iveta",
    (5, 28): "Viliam",
    (5, 29): "Vilma",
    (5, 30): "Ferdinand",
    (5, 31): "Petronela, Petrana",
    (6, 1): "Žaneta",
    (6, 2): "Xénia",
    (6, 3): "Karolína",
    (6, 4): "Lenka",
    (6, 5): "Laura",
    (6, 6): "Norbert",
    (6, 7): "Róbert",
    (6, 8): "Medard",
    (6, 9): "Stanislava",
    (6, 10): "Margaréta",
    (6, 11): "Dobrota",
    (6, 12): "Zlatko",
    (6, 13): "Anton",
    (6, 14): "Vasil",
    (6, 15): "Vít",
    (6, 16): "Blanka",
    (6, 17): "Adolf",
    (6, 18): "Vratislav",
    (6, 19): "Alfréd",
    (6, 20): "Valéria",
    (6, 21): "Alojz",
    (6, 22): "Paulína",
    (6, 23): "Sidónia",
    (6, 24): "Ján",
    (6, 25): "Olívia",
    (6, 26): "Adriána",
    (6, 27): "Ladislav, Ladislava",
    (6, 28): "Beáta",
    (6, 29): "Peter, Pavol, Petra",
    (6, 30): "Melánia",
    (7, 1): "Diana",
    (7, 2): "Berta",
    (7, 3): "Miloslav",
    (7, 4): "Prokop",
    (7, 5): "Cyril, Metod",
    (7, 6): "Patrícia",
    (7, 7): "Oliver",
    (7, 8): "Ivan",
    (7, 9): "Lujza",
    (7, 10): "Amália",
    (7, 11): "Milota",
    (7, 12): "Nina",
    (7, 13): "Margita",
    (7, 14): "Kamil",
    (7, 15): "Henrich",
    (7, 16): "Drahomír",
    (7, 17): "Bohuslav",
    (7, 18): "Kamila",
    (7, 19): "Dušana",
    (7, 20): "Iľja, Eliáš",
    (7, 21): "Daniel",
    (7, 22): "Magdaléna",
    (7, 23): "Oľga",
    (7, 24): "Vladimír",
    (7, 25): "Jakub, Timur",
    (7, 26): "Anna, Hana",
    (7, 27): "Božena",
    (7, 28): "Krištof",
    (7, 29): "Marta",
    (7, 30): "Libuša",
    (7, 31): "Ignác",
    (8, 1): "Božidara",
    (8, 2): "Gustav",
    (8, 3): "Jerguš",
    (8, 4): "Dominik, Dominika",
    (8, 5): "Hortenzia",
    (8, 6): "Jozefína",
    (8, 7): "Štefánia",
    (8, 8): "Oskar",
    (8, 9): "Ľubomíra",
    (8, 10): "Vavrinec",
    (8, 11): "Zuzana",
    (8, 12): "Darina",
    (8, 13): "Ľubomír",
    (8, 14): "Mojmír",
    (8, 15): "Marcela",
    (8, 16): "Leonard",
    (8, 17): "Milica",
    (8, 18): "Elena, Helena",
    (8, 19): "Lýdia",
    (8, 20): "Anabela",
    (8, 21): "Jana",
    (8, 22): "Tichomír",
    (8, 23): "Filip",
    (8, 24): "Bartolomej",
    (8, 25): "Ľudovít",
    (8, 26): "Samuel",
    (8, 27): "Silvia",
    (8, 28): "Augustín",
    (8, 29): "Nikola, Nikolaj",
    (8, 30): "Ružena",
    (8, 31): "Nora",
    (9, 1): "Drahoslava",
    (9, 2): "Linda",
    (9, 3): "Belo",
    (9, 4): "Rozália",
    (9, 5): "Regina",
    (9, 6): "Alica",
    (9, 7): "Marianna",
    (9, 8): "Miriama",
    (9, 9): "Martina",
    (9, 10): "Oleg",
    (9, 11): "Bystrík",
    (9, 12): "Mária",
    (9, 13): "Ctibor",
    (9, 14): "Ľudomil",
    (9, 15): "Jolana",
    (9, 16): "Ľudmila",
    (9, 17): "Olympia",
    (9, 18): "Eugénia",
    (9, 19): "Konštantín",
    (9, 20): "Ľuboslav, Ľuboslava",
    (9, 21): "Matúš",
    (9, 22): "Móric",
    (9, 23): "Zdenka",
    (9, 24): "Ľuboš",
    (9, 25): "Vladislav, Vladislava",
    (9, 26): "Edita",
    (9, 27): "Cyprián",
    (9, 28): "Václav",
    (9, 29): "Michal, Michaela",
    (9, 30): "Jarolím",
    (10, 1): "Arnold",
    (10, 2): "Levoslav",
    (10, 3): "Stela",
    (10, 4): "František",
    (10, 5): "Viera",
    (10, 6): "Natália",
    (10, 7): "Eliška",
    (10, 8): "Brigita",
    (10, 9): "Dionýz",
    (10, 10): "Slavomíra",
    (10, 11): "Valentína",
    (10, 12): "Maximilián",
    (10, 13): "Koloman",
    (10, 14): "Boris",
    (10, 15): "Terézia",
    (10, 16): "Vladimíra",
    (10, 17): "Hedviga",
    (10, 18): "Lukáš",
    (10, 19): "Kristián",
    (10, 20): "Vendelín",
    (10, 21): "Uršuľa",
    (10, 22): "Sergej",
    (10, 23): "Alojzia",
    (10, 24): "Kvetoslava",
    (10, 25): "Aurel",
    (10, 26): "Demeter",
    (10, 27): "Sabína",
    (10, 28): "Dobromila",
    (10, 29): "Klára",
    (10, 30): "Simona, Šimon",
    (10, 31): "Aurélia",
    (11, 1): "Denis, Denisa",
    (11, 2): "Pamiatka zosnulých",
    (11, 3): "Hubert",
    (11, 4): "Karol",
    (11, 5): "Imrich",
    (11, 6): "Renáta",
    (11, 7): "René",
    (11, 8): "Bohumír",
    (11, 9): "Teodor",
    (11, 10): "Tibor",
    (11, 11): "Martin, Maroš",
    (11, 12): "Svätopluk",
    (11, 13): "Stanislav",
    (11, 14): "Irma",
    (11, 15): "Leopold",
    (11, 16): "Agnesa",
    (11, 17): "Klaudia",
    (11, 18): "Eugen",
    (11, 19): "Alžbeta",
    (11, 20): "Félix",
    (11, 21): "Elvíra",
    (11, 22): "Cecília",
    (11, 23): "Klement",
    (11, 24): "Emília",
    (11, 25): "Katarína",
    (11, 26): "Kornel",
    (11, 27): "Milan",
    (11, 28): "Henrieta",
    (11, 29): "Vratko",
    (11, 30): "Ondrej, Andrej",
    (12, 1): "Edmund",
    (12, 2): "Bibiána",
    (12, 3): "Oldrich",
    (12, 4): "Barbora",
    (12, 5): "Oto",
    (12, 6): "Mikuláš",
    (12, 7): "Ambróz",
    (12, 8): "Marína",
    (12, 9): "Izabela",
    (12, 10): "Radúz",
    (12, 11): "Hilda",
    (12, 12): "Otília",
    (12, 13): "Lucia",
    (12, 14): "Branislava, Bronislava",
    (12, 15): "Ivica",
    (12, 16): "Albína",
    (12, 17): "Kornélia",
    (12, 18): "Sláva, Slávka",
    (12, 19): "Judita",
    (12, 20): "Dagmara",
    (12, 21): "Bohdan",
    (12, 22): "Adela",
    (12, 23): "Nadežda",
    (12, 24): "Adam, Eva",
    (12, 25): "1. sviatok vianočný",
    (12, 26): "Štefan",
    (12, 27): "Filoména",
    (12, 28): "Ivana",
    (12, 29): "Milada",
    (12, 30): "Dávid",
    (12, 31): "Silvester",
}

# Czech name days (month, day): names
NAME_DAYS_CS: Final = {
    (1, 1): "Nový rok",
    (1, 2): "Karina",
    (1, 3): "Radmila",
    (1, 4): "Diana",
    (1, 5): "Dalimil",
    (1, 6): "Tři králové",
    (1, 7): "Vilma",
    (1, 8): "Čestmír",
    (1, 9): "Vladan",
    (1, 10): "Břetislav",
    (1, 11): "Bohdana",
    (1, 12): "Pravoslav",
    (1, 13): "Edita",
    (1, 14): "Radovan",
    (1, 15): "Alice",
    (1, 16): "Ctirad",
    (1, 17): "Drahoslav",
    (1, 18): "Vladislav",
    (1, 19): "Doubravka",
    (1, 20): "Ilona",
    (1, 21): "Běla",
    (1, 22): "Slavomír",
    (1, 23): "Zdeněk",
    (1, 24): "Milena",
    (1, 25): "Miloš",
    (1, 26): "Zora",
    (1, 27): "Ingrid",
    (1, 28): "Otýlie",
    (1, 29): "Zdislava",
    (1, 30): "Robin",
    (1, 31): "Marika",
    (2, 1): "Hynek",
    (2, 2): "Nela",
    (2, 3): "Blažej",
    (2, 4): "Jarmila",
    (2, 5): "Dobromila",
    (2, 6): "Vanda",
    (2, 7): "Veronika",
    (2, 8): "Milada",
    (2, 9): "Apolena",
    (2, 10): "Mojmír",
    (2, 11): "Božena",
    (2, 12): "Slavěna",
    (2, 13): "Věnceslav",
    (2, 14): "Valentýn",
    (2, 15): "Jiřina",
    (2, 16): "Ljuba",
    (2, 17): "Miloslava",
    (2, 18): "Gizela",
    (2, 19): "Patrik",
    (2, 20): "Oldřich",
    (2, 21): "Lenka",
    (2, 22): "Petr",
    (2, 23): "Svatopluk",
    (2, 24): "Matěj",
    (2, 25): "Liliana",
    (2, 26): "Dorota",
    (2, 27): "Alexandr",
    (2, 28): "Lumír",
    (2, 29): "Horymír",
    (3, 1): "Bedřich",
    (3, 2): "Anežka",
    (3, 3): "Kamil",
    (3, 4): "Stela",
    (3, 5): "Kazimír",
    (3, 6): "Miroslav",
    (3, 7): "Tomáš",
    (3, 8): "Gabriela",
    (3, 9): "Františka",
    (3, 10): "Viktorie",
    (3, 11): "Anděla",
    (3, 12): "Řehoř",
    (3, 13): "Růžena",
    (3, 14): "Rút, Matylda",
    (3, 15): "Ida",
    (3, 16): "Elena, Herbert",
    (3, 17): "Vlastimil",
    (3, 18): "Eduard",
    (3, 19): "Josef",
    (3, 20): "Světlana",
    (3, 21): "Radek",
    (3, 22): "Leona",
    (3, 23): "Ivona",
    (3, 24): "Gabriel",
    (3, 25): "Marián",
    (3, 26): "Emanuel",
    (3, 27): "Dita",
    (3, 28): "Soňa",
    (3, 29): "Taťána",
    (3, 30): "Arnošt",
    (3, 31): "Kvido",
    (4, 1): "Hugo",
    (4, 2): "Erika",
    (4, 3): "Richard",
    (4, 4): "Ivana",
    (4, 5): "Miroslava",
    (4, 6): "Vendula",
    (4, 7): "Heřman, Hermína",
    (4, 8): "Ema",
    (4, 9): "Dušan",
    (4, 10): "Darja",
    (4, 11): "Izabela",
    (4, 12): "Julius",
    (4, 13): "Aleš",
    (4, 14): "Vincenc",
    (4, 15): "Anastázie",
    (4, 16): "Irena",
    (4, 17): "Rudolf",
    (4, 18): "Valérie",
    (4, 19): "Rostislav",
    (4, 20): "Marcela",
    (4, 21): "Alexandra",
    (4, 22): "Evženie",
    (4, 23): "Vojtěch",
    (4, 24): "Jiří",
    (4, 25): "Marek",
    (4, 26): "Oto",
    (4, 27): "Jaroslav",
    (4, 28): "Vlastislav",
    (4, 29): "Robert",
    (4, 30): "Blahoslav",
    (5, 1): "Svátek práce",
    (5, 2): "Zikmund",
    (5, 3): "Alexej",
    (5, 4): "Květoslav",
    (5, 5): "Klaudie",
    (5, 6): "Radoslav",
    (5, 7): "Stanislav",
    (5, 8): "Den vítězství",
    (5, 9): "Ctibor",
    (5, 10): "Blažena",
    (5, 11): "Svatava",
    (5, 12): "Pankrác",
    (5, 13): "Servác",
    (5, 14): "Bonifác",
    (5, 15): "Žofie",
    (5, 16): "Přemysl",
    (5, 17): "Aneta",
    (5, 18): "Nataša",
    (5, 19): "Ivo",
    (5, 20): "Zbyšek",
    (5, 21): "Monika",
    (5, 22): "Emil",
    (5, 23): "Vladimír",
    (5, 24): "Jana",
    (5, 25): "Viola",
    (5, 26): "Filip",
    (5, 27): "Valdemar",
    (5, 28): "Vilém",
    (5, 29): "Maxmilián",
    (5, 30): "Ferdinand",
    (5, 31): "Kamila",
    (6, 1): "Laura",
    (6, 2): "Jarmil",
    (6, 3): "Tamara",
    (6, 4): "Dalibor",
    (6, 5): "Dobroslav",
    (6, 6): "Norbert",
    (6, 7): "Iveta, Slavoj",
    (6, 8): "Medard",
    (6, 9): "Stanislava",
    (6, 10): "Gita",
    (6, 11): "Bruno",
    (6, 12): "Antonie",
    (6, 13): "Antonín",
    (6, 14): "Roland",
    (6, 15): "Vít",
    (6, 16): "Zbyněk",
    (6, 17): "Adolf",
    (6, 18): "Milan",
    (6, 19): "Leoš",
    (6, 20): "Květa",
    (6, 21): "Alois",
    (6, 22): "Pavla",
    (6, 23): "Zdeňka",
    (6, 24): "Jan",
    (6, 25): "Ivan",
    (6, 26): "Adriana",
    (6, 27): "Ladislav",
    (6, 28): "Lubomír",
    (6, 29): "Petr a Pavel",
    (6, 30): "Šárka",
    (7, 1): "Jaroslava",
    (7, 2): "Patricie",
    (7, 3): "Radomír",
    (7, 4): "Prokop",
    (7, 5): "Cyril a Metoděj",
    (7, 6): "Mistr Jan Hus",
    (7, 7): "Bohuslava",
    (7, 8): "Nora",
    (7, 9): "Drahoslava",
    (7, 10): "Libuše, Amálie",
    (7, 11): "Olga",
    (7, 12): "Bořek",
    (7, 13): "Markéta",
    (7, 14): "Karolína",
    (7, 15): "Jindřich",
    (7, 16): "Luboš",
    (7, 17): "Martina",
    (7, 18): "Drahomíra",
    (7, 19): "Čeněk",
    (7, 20): "Ilja",
    (7, 21): "Vítězslav",
    (7, 22): "Magdaléna",
    (7, 23): "Libor",
    (7, 24): "Kristýna",
    (7, 25): "Jakub",
    (7, 26): "Anna",
    (7, 27): "Věroslav",
    (7, 28): "Viktor",
    (7, 29): "Marta",
    (7, 30): "Bořivoj",
    (7, 31): "Ignác",
    (8, 1): "Oskar",
    (8, 2): "Gustav",
    (8, 3): "Miluše",
    (8, 4): "Dominik",
    (8, 5): "Kristian",
    (8, 6): "Oldřiška",
    (8, 7): "Lada",
    (8, 8): "Soběslav",
    (8, 9): "Roman",
    (8, 10): "Vavřinec",
    (8, 11): "Zuzana",
    (8, 12): "Klára",
    (8, 13): "Alena",
    (8, 14): "Alan",
    (8, 15): "Hana",
    (8, 16): "Jáchym",
    (8, 17): "Petra",
    (8, 18): "Helena",
    (8, 19): "Ludvík",
    (8, 20): "Bernard",
    (8, 21): "Johana",
    (8, 22): "Bohuslav",
    (8, 23): "Sandra",
    (8, 24): "Bartoloměj",
    (8, 25): "Radim",
    (8, 26): "Luděk",
    (8, 27): "Otakar",
    (8, 28): "Augustýn",
    (8, 29): "Evelína",
    (8, 30): "Vladěna",
    (8, 31): "Pavlína",
    (9, 1): "Linda, Samuel",
    (9, 2): "Adéla",
    (9, 3): "Bronislav",
    (9, 4): "Jindřiška",
    (9, 5): "Boris",
    (9, 6): "Boleslav",
    (9, 7): "Regína",
    (9, 8): "Mariana",
    (9, 9): "Daniela",
    (9, 10): "Irma",
    (9, 11): "Denisa",
    (9, 12): "Marie",
    (9, 13): "Lubor",
    (9, 14): "Radka",
    (9, 15): "Jolana",
    (9, 16): "Ludmila",
    (9, 17): "Naděžda",
    (9, 18): "Kryštof",
    (9, 19): "Zita",
    (9, 20): "Oleg",
    (9, 21): "Matouš",
    (9, 22): "Darina",
    (9, 23): "Berta",
    (9, 24): "Jaromír",
    (9, 25): "Zlata",
    (9, 26): "Andrea",
    (9, 27): "Jonáš",
    (9, 28): "Václav",
    (9, 29): "Michal",
    (9, 30): "Jeroným",
    (10, 1): "Igor",
    (10, 2): "Olivie, Oliver",
    (10, 3): "Bohumil",
    (10, 4): "František",
    (10, 5): "Eliška",
    (10, 6): "Hanuš",
    (10, 7): "Justýna",
    (10, 8): "Věra",
    (10, 9): "Štefan, Sára",
    (10, 10): "Marina",
    (10, 11): "Andrej",
    (10, 12): "Marcel",
    (10, 13): "Renáta",
    (10, 14): "Agáta",
    (10, 15): "Tereza",
    (10, 16): "Havel",
    (10, 17): "Hedvika",
    (10, 18): "Lukáš",
    (10, 19): "Michaela",
    (10, 20): "Vendelín",
    (10, 21): "Brigita",
    (10, 22): "Sabina",
    (10, 23): "Teodor",
    (10, 24): "Nina",
    (10, 25): "Beáta",
    (10, 26): "Erik",
    (10, 27): "Šarlota, Zoe",
    (10, 28): "Den vzniku Československa",
    (10, 29): "Silvie",
    (10, 30): "Tadeáš",
    (10, 31): "Štěpánka",
    (11, 1): "Felix",
    (11, 2): "Památka zesnulých",
    (11, 3): "Hubert",
    (11, 4): "Karel",
    (11, 5): "Miriam",
    (11, 6): "Liběna",
    (11, 7): "Saskie",
    (11, 8): "Bohumír",
    (11, 9): "Bohdan",
    (11, 10): "Evžen",
    (11, 11): "Martin",
    (11, 12): "Benedikt",
    (11, 13): "Tibor",
    (11, 14): "Sáva",
    (11, 15): "Leopold",
    (11, 16): "Otmar",
    (11, 17): "Mahulena",
    (11, 18): "Romana",
    (11, 19): "Alžběta",
    (11, 20): "Nikola",
    (11, 21): "Albert",
    (11, 22): "Cecílie",
    (11, 23): "Klement",
    (11, 24): "Emílie",
    (11, 25): "Kateřina",
    (11, 26): "Artur",
    (11, 27): "Xenie",
    (11, 28): "René",
    (11, 29): "Zina",
    (11, 30): "Ondřej",
    (12, 1): "Iva",
    (12, 2): "Blanka",
    (12, 3): "Svatoslav",
    (12, 4): "Barbora",
    (12, 5): "Jitka",
    (12, 6): "Mikuláš",
    (12, 7): "Benjamín, Ambrož",
    (12, 8): "Květoslava",
    (12, 9): "Vratislav",
    (12, 10): "Julie",
    (12, 11): "Dana",
    (12, 12): "Simona",
    (12, 13): "Lucie",
    (12, 14): "Lýdie",
    (12, 15): "Radana",
    (12, 16): "Albína",
    (12, 17): "Daniel",
    (12, 18): "Miloslav",
    (12, 19): "Ester",
    (12, 20): "Dagmar",
    (12, 21): "Natálie",
    (12, 22): "Šimon",
    (12, 23): "Vlasta",
    (12, 24): "Adam a Eva",
    (12, 25): "1. svátek vánoční",
    (12, 26): "Štěpán",
    (12, 27): "Žaneta",
    (12, 28): "Bohumila",
    (12, 29): "Judita",
    (12, 30): "David",
    (12, 31): "Silvestr",
}

# Moon phase names
MOON_PHASES_CS: Final = {
    "new_moon": "Nov",
    "waxing_crescent": "Dorůstající srpek",
    "first_quarter": "První čtvrť",
    "waxing_gibbous": "Dorůstající měsíc",
    "full_moon": "Úplněk",
    "waning_gibbous": "Couvající měsíc",
    "last_quarter": "Poslední čtvrť",
    "waning_crescent": "Couvající srpek",
}

MOON_PHASES_EN: Final = {
    "new_moon": "New Moon",
    "waxing_crescent": "Waxing Crescent",
    "first_quarter": "First Quarter",
    "waxing_gibbous": "Waxing Gibbous",
    "full_moon": "Full Moon",
    "waning_gibbous": "Waning Gibbous",
    "last_quarter": "Last Quarter",
    "waning_crescent": "Waning Crescent",
}

MOON_PHASE_ICONS: Final = {
    "new_moon": "mdi:moon-new",
    "waxing_crescent": "mdi:moon-waxing-crescent",
    "first_quarter": "mdi:moon-first-quarter",
    "waxing_gibbous": "mdi:moon-waxing-gibbous",
    "full_moon": "mdi:moon-full",
    "waning_gibbous": "mdi:moon-waning-gibbous",
    "last_quarter": "mdi:moon-last-quarter",
    "waning_crescent": "mdi:moon-waning-crescent",
}

# Seasons
SEASONS_CS: Final = {
    "spring": "Jaro",
    "summer": "Léto",
    "autumn": "Podzim",
    "winter": "Zima",
}

SEASONS_EN: Final = {
    "spring": "Spring",
    "summer": "Summer",
    "autumn": "Autumn",
    "winter": "Winter",
}

SEASON_ICONS: Final = {
    "spring": "mdi:flower",
    "summer": "mdi:white-balance-sunny",
    "autumn": "mdi:leaf",
    "winter": "mdi:snowflake",
}

# Zodiac signs with date ranges (month, day) start and end
ZODIAC_SIGNS: Final = {
    "aries": ((3, 21), (4, 19)),
    "taurus": ((4, 20), (5, 20)),
    "gemini": ((5, 21), (6, 20)),
    "cancer": ((6, 21), (7, 22)),
    "leo": ((7, 23), (8, 22)),
    "virgo": ((8, 23), (9, 22)),
    "libra": ((9, 23), (10, 22)),
    "scorpio": ((10, 23), (11, 21)),
    "sagittarius": ((11, 22), (12, 21)),
    "capricorn": ((12, 22), (1, 19)),
    "aquarius": ((1, 20), (2, 18)),
    "pisces": ((2, 19), (3, 20)),
}

ZODIAC_CS: Final = {
    "aries": "Beran",
    "taurus": "Býk",
    "gemini": "Blíženci",
    "cancer": "Rak",
    "leo": "Lev",
    "virgo": "Panna",
    "libra": "Váhy",
    "scorpio": "Štír",
    "sagittarius": "Střelec",
    "capricorn": "Kozoroh",
    "aquarius": "Vodnář",
    "pisces": "Ryby",
}

ZODIAC_EN: Final = {
    "aries": "Aries",
    "taurus": "Taurus",
    "gemini": "Gemini",
    "cancer": "Cancer",
    "leo": "Leo",
    "virgo": "Virgo",
    "libra": "Libra",
    "scorpio": "Scorpio",
    "sagittarius": "Sagittarius",
    "capricorn": "Capricorn",
    "aquarius": "Aquarius",
    "pisces": "Pisces",
}

ZODIAC_ICONS: Final = {
    "aries": "mdi:zodiac-aries",
    "taurus": "mdi:zodiac-taurus",
    "gemini": "mdi:zodiac-gemini",
    "cancer": "mdi:zodiac-cancer",
    "leo": "mdi:zodiac-leo",
    "virgo": "mdi:zodiac-virgo",
    "libra": "mdi:zodiac-libra",
    "scorpio": "mdi:zodiac-scorpio",
    "sagittarius": "mdi:zodiac-sagittarius",
    "capricorn": "mdi:zodiac-capricorn",
    "aquarius": "mdi:zodiac-aquarius",
    "pisces": "mdi:zodiac-pisces",
}

# Default sensors to enable
DEFAULT_SENSORS: Final = [
    SENSOR_DATE,
    SENSOR_DAY_NAME,
    SENSOR_WEEK_NUMBER,
]

# Update interval (in minutes)
UPDATE_INTERVAL: Final = 1
